In [1]:
import numpy as np

In [2]:
c = np.full((2,3),10)
c

array([[10, 10, 10],
       [10, 10, 10]])

In [3]:
type(c)

numpy.ndarray

In [4]:
a = np.array([[1,2],[4,5]])
b = np.array([[1,2],[4,5,]])

In [5]:
a + [7]

array([[ 8,  9],
       [11, 12]])

In [6]:
a * 2

array([[ 2,  4],
       [ 8, 10]])

In [7]:
a * b

array([[ 1,  4],
       [16, 25]])

In [8]:
np.dot(a, b)

array([[ 9, 12],
       [24, 33]])

In [9]:
a.dot(b)

array([[ 9, 12],
       [24, 33]])

In [13]:
rand = np.random.randn(5000,5000)

In [14]:
rand.mean()

0.00010368300629767091

In [16]:
rand.min()

-5.200151075281582

In [17]:
np.random.randint(1,31,30)

array([21,  4, 16, 12,  3, 25, 23, 16, 23, 21, 30, 16, 21, 21,  9, 24, 19,
       12,  1, 23, 17, 18, 15, 18, 26, 18, 28,  2, 18, 30])

In [18]:
trans_A = np.linalg.inv(a)
trans_A

array([[-1.66666667,  0.66666667],
       [ 1.33333333, -0.33333333]])

In [19]:
a

array([[1, 2],
       [4, 5]])

In [20]:
np.dot(a, trans_A)

array([[1., 0.],
       [0., 1.]])

In [21]:
a.T

array([[1, 4],
       [2, 5]])